# Generated by Django 2.0.1 on 2018-02-10 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Укажите свой пол', max_length=20)),
                ('automatic_greeting', models.BooleanField(default=True)),
            ],
        ),
    ]
