# Generated by Django 2.0.1 on 2018-03-08 14:52

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Укажите свой пол', max_length=20)),
                ('automatic_greeting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='addperson',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete='DO_NOTHING', to='contact.ContactUser'),
        ),
    ]
