# Generated by Django 2.0.1 on 2018-02-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_createusr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUsr',
        ),
    ]
