# Generated by Django 2.0.1 on 2018-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_person', '0002_addperson_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addperson',
            old_name='l',
            new_name='automatic_greeting',
        ),
    ]
