# Generated by Django 2.0.1 on 2018-02-05 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_person', '0003_auto_20180205_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='addperson',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
